#
# Current best known config for meta-training on Mini-ImageNet.
#

# Dataset
dataset: miniimagenet
train_size: 500

# Training Configuration
train_method: meta
lobotomize: false
batch_size: 1
num_batches: 20
train_cycles: 1
val_sample_size: 200
remember_size: 100
remember_only: false
inner_lr: 0.001
outer_lr: 0.001

epochs: 25000
seed: 1

# Model Architecture
model: classifier
model_name: resnet18
model_args:
  encoder: resnet18
  encoder_args: {}
  classifier: linear-classifier
  classifier_args: {num_classes: 64}

# Optimization Configuration
inner_params: classifier
outer_params: all
output_layer: classifier.linear

eval_steps: [10000, 25000]
eval:
  - no-sgd: !include eval-inet-zero-shot.yml
  - olft: !include eval-sweep-inet-1FC.yml
  - unfrozen: !include eval-sweep-inet-unfrozen.yml
  - lstsq-unfrozen: !include eval-sweep-inet-lstsq-unfrozen.yml
  - iid-olft: !include eval-sweep-inet-iid-1FC.yml
  - iid-unfrozen: !include eval-sweep-inet-iid-unfrozen.yml
  - iid-lstsq-unfrozen: !include eval-sweep-inet-iid-lstsq-unfrozen.yml
